# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-10 01:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='EdgeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('data', models.CharField(max_length=200)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sem_graph.Graph')),
            ],
        ),
        migrations.AddField(
            model_name='edgetype',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sem_graph.Graph'),
        ),
        migrations.AddField(
            model_name='edge',
            name='edgetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sem_graph.EdgeType'),
        ),
        migrations.AddField(
            model_name='edge',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sem_graph.Graph'),
        ),
        migrations.AddField(
            model_name='edge',
            name='node1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outedges', to='sem_graph.Node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='node2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inedges', to='sem_graph.Node'),
        ),
    ]
