# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-12-10 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sem_graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='edgetype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sem_graph.EdgeType'),
        ),
    ]
